# Generated by Django 2.2.6 on 2020-01-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbAbogados',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=51)),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True)),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('tarjeta_p', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=154, null=True)),
                ('ciudadnombre', models.CharField(blank=True, db_column='ciudadNombre', max_length=27, null=True)),
                ('departamento', models.CharField(blank=True, max_length=18, null=True)),
                ('direccion2', models.CharField(blank=True, max_length=154, null=True)),
                ('empresa', models.CharField(blank=True, max_length=56, null=True)),
                ('celular2', models.CharField(blank=True, max_length=15, null=True)),
                ('celular1', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('fijo2', models.CharField(blank=True, max_length=15, null=True)),
                ('fijo1', models.CharField(blank=True, max_length=15, null=True)),
                ('fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('e_mail1', models.CharField(blank=True, max_length=67, null=True)),
                ('e_mail2', models.CharField(blank=True, max_length=67, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('fechaexpedicion', models.DateField(blank=True, db_column='fechaExpedicion', null=True)),
            ],
            options={
                'db_table': 'db_abogados',
                'managed': False,
            },
        ),
    ]
