# Generated by Django 2.2.6 on 2020-01-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0002_auto_20200117_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbabogados',
            options={'managed': True, 'ordering': ['codigo'], 'verbose_name': 'Abogado', 'verbose_name_plural': 'Informe de DB_ABOGADOS'},
        ),
    ]
