# Generated by Django 2.2.6 on 2020-01-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_dane', models.CharField(max_length=15)),
                ('departamento', models.CharField(max_length=18)),
                ('municipio', models.CharField(max_length=27)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
    ]
