# Generated by Django 2.2.6 on 2020-01-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipio', '0001_initial'),
        ('perfil_asesor', '0001_initial'),
        ('comisiones', '0001_initial'),
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsesoresDb',
            fields=[
                ('cod_asesor', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=154, null=True)),
                ('direccion2', models.CharField(blank=True, max_length=154, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('t_asesor', models.CharField(blank=True, max_length=15, null=True)),
                ('cedula', models.CharField(blank=True, max_length=15, null=True)),
                ('c_cedula', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_s', models.DateTimeField(auto_now=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('fechaexpedicion', models.DateField(blank=True, db_column='fechaExpedicion', null=True)),
                ('ciudad', models.ForeignKey(blank=True, db_column='ciudad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AsesoresDb.ciudad+', to='municipio.Municipio')),
                ('ciudad2', models.ForeignKey(blank=True, db_column='ciudad2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AsesoresDb.ciudad2+', to='municipio.Municipio')),
                ('ciudadexpedicion', models.ForeignKey(blank=True, db_column='ciudadExpedicion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AsesoresDb.ciudadexpedicion+', to='municipio.Municipio')),
                ('comision', models.ForeignKey(blank=True, db_column='comision', null=True, on_delete=django.db.models.deletion.PROTECT, to='comisiones.Comisiones')),
                ('genero', models.ForeignKey(db_column='genero', on_delete=django.db.models.deletion.PROTECT, to='genero.Genero')),
                ('perfil', models.ForeignKey(blank=True, db_column='perfil', null=True, on_delete=django.db.models.deletion.PROTECT, to='perfil_asesor.Perfilasesor')),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
                'db_table': 'asesores_db',
                'ordering': ['cod_asesor'],
                'managed': True,
            },
        ),
    ]
