# Generated by Django 2.2.6 on 2020-01-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0002_auto_20200122_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesoresdb',
            name='municipio',
        ),
        migrations.AddField(
            model_name='asesoresdb',
            name='departamento',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
