# Generated by Django 2.2.6 on 2020-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenContacto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'origen_contacto',
                'managed': False,
            },
        ),
    ]
